### ISSUE TITLE
Travis tests are failing

### ISSUE THREAD

**Issue by makoto** [ensdomains/dnssec-oracle#11]
Currently travis tests are failing because the test assumes that `tx.receipt.status` to retun `0x0` when the transaction reverted while ganache raises exception.

```
async function verifyFailedSubmission(instance, name, data, sig) {
  var name = dns.hexEncodeName(name);
  var tx = await instance.submitRRSet(1, name, data, sig);
  assert.equal(tx.receipt.status, "0x0");
  return tx;
}
```

The potential solutions are 

1. Wait until Ganache implements correct behavior
2. Catch all reverts and test that certain state did not check.
3. Anything else?

**Comment by Arachnid** [comment]
Fixed, I believe.
