### ISSUE TITLE
Add support to DNSSEC algorithm 13

### ISSUE THREAD

**Issue by rittme** [ensdomains/dnssec-oracle#74]
Domains using cloudflare dns are only allowed to use ECDSA (which they argue is better).
Would be nice if dnssec-oracle supported Algorithm 13, ECDSA, so we can also use our domains hosted on cloudflare.

**Comment by Arachnid** [comment]
We already added support for this, [here](https://github.com/ensdomains/dnssec-oracle/blob/master/contracts/algorithms/P256SHA256Algorithm.sol). It's gas-hungry, but functional.
